version: 2
jobs:
  build:
    docker:
      - image: alpline:3.10

    steps:
      - checkout

      - run:
          name: Install deps
          command: apk add build-base && apk add check-dev

      - run:
          name: Build
          command: make build

      - run:
          name: Run tests
          command: make test
