version: 2
jobs:
  all:
    docker:
      - image: alpine:3.10

    steps:
      - checkout

      - run:
          name: Install deps
          command: apk add build-base && apk add check-dev

      - run:
          name: Build
          command: make build

      - run:
          name: Check memory leak
          command: make check-leak

      - run:
          name: Run tests
          command: make test
